### ISSUE TITLE
XSD requires HPXML 4.0

### ISSUE THREAD

**Issue by BenjaminStuermer** [NREL/OpenStudio-ERI#568]
Commit https://github.com/NREL/OpenStudio-ERI/commit/6b08e8ab2723203a7918ad39e92fb6d315ea886c changed HPXMLtoOpenStudio/resources/HPXML.xsd and HPXMLtoOpenStudio/resources/HPXMLDataTypes.xsd such that HPXML version 4.0 is now required. However, HPXML version 4.0 has not been released by NREL yet; it's still in development to be released next year.

I believe that this change should be reverted and HPXML 3.0 required, as that is the most recently published version of HPXML.

**Comment by shorowit** [comment]
It's a bit confusing indeed, but this was a correct and intentional change.

Even though the HPXML schema version being required previously was "3.0", it was actually a _proposed version of 3.1_ and not the official v3.0 schema. Which is to say, we have been making use of new proposed features that have not yet been officially accepted. Perhaps we should have bumped the version to 3.1, but it is merely proposed and not yet official, and therefore any one of the proposals could still change before v3.1 is officially released.

That said, the HPXML Working Group has more recently decided to work on proposed v3.1 and proposed v4.0 schemas in parallel (see [here](https://www.youtube.com/watch?v=MoXAB9W1QA0)). v4.0 introduces some breaking changes that we wanted to use, so we have adopted that. Even though it's again not yet official, we bumped the required schema version to "4.0" to make software developers more aware of the change.

**Comment by BenjaminStuermer** [comment]
@shorowit Thanks for the explanation. It's a bit of an issue for me as a developer that the software is requiring a version of HPXML that doesn't really exist and (as far as I know) isn't documented yet, but I understand why you're doing that.
