### ISSUE TITLE
ERICalculation/Version missing from XSD

### ISSUE THREAD

**Issue by BenjaminStuermer** [NREL/OpenStudio-ERI#569]
See https://github.com/NREL/OpenStudio-ERI/blob/fe8846b187b08d8ad52f356ba0dd6dbbc3e16954/workflow/energy_rating_index.rb#L23

If the field `/HPXML/SoftwareInfo/extension/ERICalculation/Version` is not set, then a call to workflow/energy_rating_index.rb will always fail. However, the XSD file indicates that `/HPXML/SoftwareInfo/extension` is optional: https://github.com/NREL/OpenStudio-ERI/blob/fe8846b187b08d8ad52f356ba0dd6dbbc3e16954/hpxml-measures/HPXMLtoOpenStudio/resources/hpxml_schema/BaseElements.xsd#L645

The XSD should be updated to indicate that this field is mandatory, and if possible to indicate appropriate values.

**Comment by BenjaminStuermer** [comment]
I would be happy to open a PR adding the required `ERICalculation/Version` definition to the XSD, if that would be appreciated. I didn't want to open a PR before confirming that I'm actually understanding the issue correctly, though, since I'm just getting started using OpenStudio-ERI.

**Comment by shorowit** [comment]
At one point, `ERICalculation/Version` was required. But when we added the ENERGY STAR calculation, life became a bit more complicated. The ERI version is not needed if you're just running an ENERGY STAR calculation (and similarly, the ENERGY STAR version is not needed if you're just running an ERI calculation). Since we only use a single schematron file for both purposes, and we don't know whether you've created the HPXML file to run ERI, ENERGY STAR, or both, I made `ERICalculation/Version` and `EnergyStarCalculation/Version` optional and [documented](https://openstudio-eri.readthedocs.io/en/latest/workflow_inputs.html#hpxml-eri-es-calculation) that they are required inputs depending on what you're running.

There are a few ways to handle this:
1. Create separate schematron files for ERI and ENERGY STAR. I don't particularly like that since they are 99.99% the same.
2. Require both `ERICalculation/Version` and `EnergyStarCalculation/Version` in the schematron file. Also not crazy about this since it would mean that, e.g., you have to supply an ENERGY STAR version even if you're just doing an ERI calculation.
3. Remove the ERI version check in energy_rating_index.rb and default to 'latest' if not provided. That would solve your immediate issue. However, the same issue would exist for ENERGY STAR, and there it's not possible to default the version.
4. Leave it as is and accept that it's not perfect but software developers can deal with the quirks.

I lean towards option 4 but am open to other opinions.

**Comment by BenjaminStuermer** [comment]
I'm fine with option 4 from my perspective, if for no other reason than because I'm very unfamiliar with this project still and don't properly understand all the implications of the other options. Thanks for taking the time to respond to my issues.
